import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    aspectRatio: 1080 / 1920,
  },
  container: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
  },
  question: {
    fontSize: 30,
    marginVertical: 20,
    textAlign: 'center',
    color: 'white',
    fontFamily: 'Jua',
  },
  choiceContainer: {
    position: 'absolute',
    top: height * 0.560,
    left: width * 0.4,
    width: width * 0.2,
    height: height * 0.1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  choice: {
    width: '40%',
    height: '70%',
    backgroundColor: '#3b6b3b',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 30,
  },
  choiceText: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Jua',
  },
  battleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 30,
    marginTop: 120,
  },
  characterContainer: {
    alignItems: 'center',
  },
  playerImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  enemyImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  playerHPContainer: { // New style for player HP container
    width: 100,
    height: 10,
    backgroundColor: '#ccc',
    borderRadius: 5,
    marginTop: 10,
  },
  playerHPFill: { // New style for player HP fill
    height: '100%',
    backgroundColor: '#00ff00',
  },
  enemyHPContainer: {
    width: 100,
    height: 10,
    backgroundColor: '#ccc',
    borderRadius: 5,
    marginTop: 10,
  },
  enemyHPFill: {
    height: '100%',
    backgroundColor: '#ff0000',
  },
  attackEffect: {
    position: 'absolute',
    width: 50,
    height: 50,
    left: width / 2 - 25,
    top: height / 2 - 100,
    resizeMode: 'contain',
    tintColor: '#ff0000',
  },
  bottomButton: {
    position: 'absolute',
    bottom: height * 0.03,
    width: width * 0.2,
    paddingVertical: 15,
    backgroundColor: '#76C043',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bottomButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Jua',
  },
  curtainContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2, // Ensure it's on top
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Optional semi-transparent background
  },
  curtainLeft: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '50%',
    height: '100%',
    backgroundColor: '#000',
  },
  curtainRight: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: '50%',
    height: '100%',
    backgroundColor: '#000',
  },
  curtainText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Jua',
  },
  characterName: {
    fontSize: 18,
    color: 'white',
    fontFamily: 'Jua',
    marginBottom: 5, // Adds spacing between the name and character image
    textAlign: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)', // Dark background with opacity
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  gameOverText: {
    color: '#FFFFFF',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Jua',
  },
  proceedButton: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
  },
  proceedButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  
});
